version: '2.3'

services:
  # SERVICE: Node container for running sanity.io
  node:
    env_file:
      - .env.local 
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: lagoon/node.dockerfile
    labels:
      lagoon.type: none
    volumes:
      - .:/app:delegated
    environment:
      - LAGOON_LOCALDEV_HTTP_PORT=3000
      - LAGOON_ROUTE=http://wo-template-sanity-for-nextjs.docker.amazee.io
    # Uncomment the the ports section if Sanity needs to authenticate
    #ports:
      #- "4321:4321"

networks:
  amazeeio-network:
    external: true

